version: '3'
services:
  jenkins:
    build:
      context: .
      args:
        Docker_group: 999
    ports:
      - "50000:50000"
      - "8080:8080"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      # me docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: 